DATASET: 
  TRAIN: '/home/joannekim0420/tmp/Q2A0505/encoder/outputs_/vit_b16_384_fps1/train_stage2'
  VAL: '/home/joannekim0420/tmp/Q2A0505/encoder/outputs_/vit_b16_384_fps1/test'
  TEST: '/home/joannekim0420/tmp/Q2A0505/encoder/outputs_/vit_b16_384_fps1/test'
  GT: '/home/joannekim0420/tmp/Q2A0505/data/test.json'
DATALOADER:
  NUM_WORKERS: 0
INPUT:
  QA: 'qa_maskx-1.pth'
  VIDEO: 'video_v2.pth'
  SCRIPT: 'script.pth'
  DIM: 768
  NUM_MASKS: 1
MODEL:
  ARCH: 'q2a'
  DIM_STATE: 768
  NUM_HEADS: 3
  HISTORY: 
    TRAIN: 'gt'
    VAL: 'max'
    ARCH: 'gru'  #gru mlp
  N_LAYERS : 3
SOLVER:
  LR: 0.002
  BATCH_SIZE: 16
  WARMUP_EPOCHS: 1
  MAX_EPOCHS: 100
CHECK_VAL_EVERY_N_EPOCH: 1
NUM_GPUS: 1
CKPT: "/home/S20225114/CVPR_base/outputs/khy_gru_new_stage2/epoch=71-step=792.ckpt"