DATASET: 
  ROOT: "/home/joannekim0420/tmp/Q2A0505/data"
  SPLIT: "train"
  LABEL: "train.json"
MODEL: 
  VISION: "vit_base_patch16_384"
  TEXT: "bert-base-uncased"
  CKPT_DIR: 
INPUT: 
  FPS: 1
  SIZE: [384, 384]
FOR:
  VIDEO: False
  SCRIPT: False
  QA: False
QA:
  NUM_MASKS: -1 # best performance